name: Build

on:
  push:
    branches: [ "vad" ]
  pull_request:
    branches: [ "vad" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: autogen.sh
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - uses: actions/upload-artifact@v3
      with:
        name: vad
        path: ./vad

